### PR TITLE
Add forks and projects list

### PR DESCRIPTION
**Pull request by eacousineau**
This may be a bit much, but would like to at least start cataloging some of these things, especially for people to discover different patterns or approaches to binding APIs or provide relevant features.

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Great, I'm up to merge this!

**Comment by bstaletic** [comment]
Yeah, I like this change too.

**Comment by YannickJadoul** [comment]
Great! So go ahead and merge once you're happy with this, @eacousineau! (I just saw you still force-pushed changes, so I don't want to merge this before you're done)

**Comment by henryiii** [comment]
+1 from me too

**Comment by eacousineau** [comment]
Yup, I'm good with this!
And, er, do I need some permissions to merge? It says that I need write access to do so.

**Comment by YannickJadoul** [comment]
Apparently you didn't have those yet, indeed :-)
Now you should, though? ;-)

**Comment by eacousineau** [comment]
Got 'em now, thanks!

**Pull request merged**
